version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx16g
      TERM: dumb

    steps:
      - add_ssh_keys:
          fingerprints:
            - "cc:ad:40:0f:66:d9:d9:ae:7b:48:6e:65:9f:e6:ac:be"
            - "8d:a0:f7:aa:e8:d5:41:7e:85:eb:10:71:49:16:33:c1"
            - "79:a8:2b:3d:12:40:1e:45:24:41:18:30:47:81:d9:61"
            - "c9:3f:d7:23:7a:36:05:cf:f2:ad:08:68:0b:16:57:4b"
            - "3b:70:31:86:74:31:25:e6:18:aa:ec:1b:01:d9:2d:76"
            - "7e:53:fb:00:34:99:b8:78:e6:3a:06:d7:7d:dd:01:b3"

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew specs

      - persist_to_workspace:
          root: build
          paths:
            - html

      - store_artifacts:
          path: build/html

      - run: ./.circleci/publish-website.sh

workflows:
  version: 2
  check:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
